# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Loïc Talignani"
__license__ = "GNU AGPL v3"


# CONFIGURATION #
configfile: "config/config.yaml"


import glob
import yaml

# Load configuration
with open("config/config.yaml", "r") as config_file:
    config = yaml.safe_load(config_file)

from snakemake.utils import min_version

min_version("8.9.0")

caller = config["caller"]


###############################################################################
# INCLUSION DES MODULES #
include: "rules/create_directories.smk"
include: "rules/common.smk"
include: "rules/bam_barrier.smk"
include: "rules/fastqc.smk"
include: "rules/trim.smk"
include: "rules/bwa.smk"
include: "rules/merge_bams.smk"
include: "rules/markduplicates.smk"
include: "rules/setnmtag.smk"
include: "rules/samtools_index.smk"
include: "rules/rtc.smk"
include: "rules/indlr.smk"
include: "rules/fixmateinformation.smk"
include: "rules/qualimap.smk"
include: "rules/awkforigv.smk"
include: "rules/samtools_stats.smk"
include: "rules/validatesam.smk"
include: "rules/multiqc.smk"
include: "rules/ug.smk"
include: "rules/hc.smk"
include: "rules/genomicsdb.smk"
include: "rules/gtgvcfs.smk"
include: "rules/filter_vcf.smk"
include: "rules/bcftools_stats.smk"
include: "rules/vcf_stats.smk"
include: "rules/report_vcf.smk"


################################## A L L #######################################
localrules:
    create_directories,
    create_bed_file_for_igv,
    create_bam_list,
    all_bams_ready,


# Pre-compute VCF output targets based on vcf_output_mode and enable_variant_calling.
# chromosomes and vcf_output_mode are defined in rules/common.smk.
if config.get("enable_variant_calling", True):
    _vcf_per_chrom = expand("calls/all.{chrom}.filtered.vcf.gz", chrom=chromosomes)
    _vcf_merged = ["calls/all.filtered.vcf.gz"]
    _bcftools_raw = expand(
        "qc/vcf_stats/{chrom}.raw.bcftools_stats.txt", chrom=chromosomes
    )
    _bcftools_filtered = expand(
        "qc/vcf_stats/{chrom}.filtered.bcftools_stats.txt", chrom=chromosomes
    )
    _bcftools_genome = ["qc/vcf_stats/all.filtered.bcftools_stats.txt"]
    _vcftools = expand("qc/vcf_stats/vcf_{chrom}.frq", chrom=chromosomes)
    _reports = expand("qc/vcf_stats/report_vcf_{chrom}.html", chrom=chromosomes)

    if vcf_output_mode == "per_contig":
        _vcf_outputs = _vcf_per_chrom
    elif vcf_output_mode == "merged":
        _vcf_outputs = _vcf_merged
    else:  # "both"
        _vcf_outputs = _vcf_per_chrom + _vcf_merged

    _vcf_qc = _bcftools_raw + _bcftools_filtered + _vcftools + _reports
    if vcf_output_mode != "per_contig":
        _vcf_qc += _bcftools_genome
else:
    _vcf_outputs = []
    _vcf_qc = []


if config["caller"] == "HaplotypeCaller":

    rule all:
        input:
            "logs/.directories_created",
            expand("qc/validatesam/{sample}_md.txt", sample=samples.index),
            "qc/multiqc.html",
            expand("merged/{sample}_merged.bam", sample=samples.index),
            (
                expand(
                    "calls/{sample}.{chrom}.g.vcf.gz",
                    sample=samples.index,
                    chrom=chromosomes,
                )
                if config.get("enable_variant_calling", True)
                else []
            ),
            _vcf_outputs,
            _vcf_qc,

elif config["caller"] == "UnifiedGenotyper":

    rule all:
        input:
            expand("qc/validatesam/{sample}.fixed.sorted.txt", sample=samples.index),
            expand("dedup/{sample}_realignertargetcreator.bed", sample=samples.index),
            "qc/multiqc.html",
            expand("merged/{sample}_merged.bam", sample=samples.index),
            (
                expand("calls/variants.{chrom}.vcf.gz", chrom=chromosomes)
                if config.get("enable_variant_calling", True)
                else []
            ),
            _vcf_outputs,
            _vcf_qc,

else:
    raise ValueError("Unsupported caller specified in config file.")
