rule multiqc_config:
    input:
        expand(
            "qc/fastqc/{sample}_{unit}_{read}.html",
            sample=samples.index,
            unit=units["unit"],
            read=["R1", "R2"],
        ),
        expand(
            "qc/markdup/{sample}_{unit}_sorted_md_metrics.txt",
            sample=samples.index,
            unit=units["unit"],
        ),
        expand(
            "qc/samtools/{sample}_{unit}_realigned.txt",
            sample=samples.index,
            unit=units["unit"],
        ),
        expand(
            "qc/samtools/{sample}_{unit}_md.txt",
            sample=samples.index,
            unit=units["unit"],
        ),
        expand(
            "qc/qualimap_hc/{sample}_{unit}/{sample}_{unit}_qualimapReport.html",
            sample=samples.index,
            unit=units["unit"],
        ),
        expand(
            "qc/qualimap_ug/{sample}_{unit}/{sample}_{unit}_qualimapReport.html",
            sample=samples.index,
            unit=units["unit"],
        ),
        config="config/multiqc_config.yaml",
    output:
        "qc/multiqc_report.html",
        "qc/multiqc.config_data.zip",
    params:
        extra="--verbose",
    log:
        "logs/multiqc.log",
    wrapper:
        "v4.6.0/bio/multiqc"
        